services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.sit
    image: lng-web
    ports:
      - "3009:3009"
    env_file:
      - .env.sit
    environment:
      - NODE_ENV=production
      - PORT=3009
    restart: always
